<?php

namespace Container69ojlqf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YrnANknService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yrnANkn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yrnANkn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailerService' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
        ], [
            'mailerService' => 'App\\Service\\MailerService',
        ]);
    }
}
