<?php

namespace Container69ojlqf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GfuCj4fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GfuCj4f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GfuCj4f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'schedule' => ['privates', '.errored..service_locator.GfuCj4f.App\\Entity\\Schedule', NULL, 'Cannot autowire service ".service_locator.GfuCj4f": it needs an instance of "App\\Entity\\Schedule" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'schedule' => 'App\\Entity\\Schedule',
            'em' => '?',
        ]);
    }
}
