<?php

namespace Container69ojlqf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalFeedingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fa3BW59.App\Entity\AnimalFeeding' shared service.
     *
     * @return \App\Entity\AnimalFeeding
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fa3BW59": it needs an instance of "App\\Entity\\AnimalFeeding" but this type has been excluded in "config/services.yaml".');
    }
}
