<?php

namespace Container69ojlqf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1csE2Fv.App\Controller\AnimalController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1csE2Fv.App\\Controller\\AnimalController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animal' => ['privates', '.errored..service_locator.1csE2Fv.App\\Entity\\Animal', NULL, 'Cannot autowire service ".service_locator.1csE2Fv": it needs an instance of "App\\Entity\\Animal" but this type has been excluded in "config/services.yaml".'],
            'dm' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService', true],
            'veterinaryReportRepository' => ['privates', 'App\\Repository\\VeterinaryReportRepository', 'getVeterinaryReportRepositoryService', true],
            'animalFeedingRepository' => ['privates', 'App\\Repository\\AnimalFeedingRepository', 'getAnimalFeedingRepositoryService', true],
        ], [
            'animal' => 'App\\Entity\\Animal',
            'dm' => '?',
            'veterinaryReportRepository' => 'App\\Repository\\VeterinaryReportRepository',
            'animalFeedingRepository' => 'App\\Repository\\AnimalFeedingRepository',
        ]))->withContext('App\\Controller\\AnimalController::show()', $container);
    }
}
