<?php

namespace Container69ojlqf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitat4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nvY2WDd.App\Entity\Habitat' shared service.
     *
     * @return \App\Entity\Habitat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nvY2WDd": it needs an instance of "App\\Entity\\Habitat" but this type has been excluded in "config/services.yaml".');
    }
}
