<?php

namespace Container69ojlqf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IIIjvIW.App\Controller\HabitatController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.IIIjvIW'] ?? $container->load('get_ServiceLocator_IIIjvIWService'));

        if (isset($container->privates['.service_locator.IIIjvIW.App\\Controller\\HabitatController::new()'])) {
            return $container->privates['.service_locator.IIIjvIW.App\\Controller\\HabitatController::new()'];
        }

        return $container->privates['.service_locator.IIIjvIW.App\\Controller\\HabitatController::new()'] = $a->withContext('App\\Controller\\HabitatController::new()', $container);
    }
}
