<?php

namespace Container69ojlqf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeterinaryReportControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J7bOFQQ.App\Controller\VeterinaryReportController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J7bOFQQ.App\\Controller\\VeterinaryReportController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'veterinaryReport' => ['privates', '.errored..service_locator.J7bOFQQ.App\\Entity\\VeterinaryReport', NULL, 'Cannot autowire service ".service_locator.J7bOFQQ": it needs an instance of "App\\Entity\\VeterinaryReport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'veterinaryReport' => 'App\\Entity\\VeterinaryReport',
        ]))->withContext('App\\Controller\\VeterinaryReportController::show()', $container);
    }
}
