<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container69ojlqf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container69ojlqf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container69ojlqf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container69ojlqf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container69ojlqf\App_KernelDevDebugContainer([
    'container.build_hash' => '69ojlqf',
    'container.build_id' => '3b557093',
    'container.build_time' => 1721480681,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container69ojlqf');
