name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: jurasikarcadia

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install sshpass

      - name: Copy to VPSS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          APP_PATH: /home/rene/htdocs/reneleliard.online
        run: sshpass -p "$VPS_PASSWORD" rsync -avz  --include='.*'  -e " ssh -o StrictHostKeyChecking=no " ./* $VPS_USER@$VPS_HOST:$APP_PATH

      - name: Deploy using docker-compose
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "
            cd htdocs/reneleliard.online/ && 
            ls &&
            docker compose down -v 
            docker compose up -d --build
          "
